# Modelo de configuração pre-commit para projetos Node.js
# Copie este arquivo para .pre-commit-config.yaml e ajuste conforme necessário

repos:
        
  # Catálogo central de hooks de segurança (SEMPRE usar tag específica)
  - repo: https://github.com/pcnuness/git-hooks-central.git
    rev: v1.0.2
    hooks:
      - id: secrets-detection-gitlab
        stages: [pre-push]
        always_run: true
        pass_filenames: false