# Modelo de configuração pre-commit para projetos Node.js
# Copie este arquivo para .pre-commit-config.yaml e ajuste conforme necessário

repos:
        
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2 # Use a versão mais recente
    hooks:
      - id: gitleaks
        stages: [pre-push]
        always_run: true
        pass_filenames: false